# node: 该配置文件仅用于体验环境
server:
  context-path: /shield-manage
  port: 8090
  undertow:
    io-threads: 10
    worker-threads: 50
    accesslog:
      enabled: true
      pattern: "%h %l %u %{time,[dd/MMM/yyyy:HH:mm:ss.SSS Z]} \"%r\" %s %b \"%{i,Referer}\" \"%{i,User-Agent}\""
      dir: "/app1/access-logs/shield-manage-web"
zk:
  connections: 192.168.18.13:2181,192.168.18.59:2181,192.168.18.61:2181
  connection-timeout-ms: 3000
  session-timeout-ms: 5000
  max-retries: 5
  base-sleep-time-ms: 1000

# log file
logging:
  stash:
    destination: "192.168.18.63:5046"

spring:
  redis:
    cluster:
      nodes: 192.168.18.13:8020,192.168.18.13:8021,192.168.18.13:8022,192.168.18.13:8023,192.168.18.13:8024,192.168.18.13:8025
    timeout: 10000
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: 2000
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 30Mb

shiro:
  enabled: true
  render-page-mode: false
  session:
    prefix: "jssessionid:"
    time-out-hours: 2
  hashed-credential:
    hash-algorith-name: md5
    hash-iterations: 3
  cache:
    authorization-caching-enabled: true
    authenticationCachePrefix: "sd-web-ac:" #sd-web.shiro-authentication
    authorizationCachePrefix: "sd-web-az:"  #sd-web.shiro-authorization

#base-rul上传服务地址需要修改
file-upload:
  application-name: ${spring.application.name}
  base-url:
  base-path: "/mfstestdir/data"
  image:
    ext-names: jpg,png,gif,tif,bmp
    max-height: 3000
    max-width: 3000
    max-size: 5242880
    small-height: 100
    small-width: 0
  attachment:
    ext-names: jpg,png,jpeg,doc,docx,xlsx,xls,pdf,zip,rar
    max-size: 10485760